### ISSUE TITLE
Is quantized yolov5 available in the repo?

### ISSUE THREAD

**Issue by lzmz08** [sefaburakokcu/quantized-yolov5#30]
## ❔Question
 Is quantized yolov5 available in the repo?

## Additional context
I could see only the quantized yolov1 model using the quantized layers. So are quantized yolov5 models available in this repo or do I need to build them using the quantized layers?

**Comment by sefaburakokcu** [comment]
Hi,
We used only quantized Yolov1 in our experiments. But, you can replace Yolov5's layers with Quantized alternatives, and use our repository for training it.
