### ISSUE TITLE
Result reproduction

### ISSUE THREAD

**Issue by giovannipollo** [sefaburakokcu/quantized-yolov5#39]
Hi, I'm trying to reproduce your results with yolov1-tiny model. How did you convert the data of widerface into a correct format? Cause when I download the zip it only contains images.

Thanks for the great work!

**Comment by sefaburakokcu** [comment]
The issue is closed due to inactivity. If you have any questions, feel free to open a new issue.

**Comment by thetushargoyal** [comment]
@giovannipollo Were you able to solve it?

**Comment by giovannipollo** [comment]
@thetushargoyal a lot of time has passed, but I did not solved it back in time

**Comment by thetushargoyal** [comment]
> @thetushargoyal a lot of time has passed, but I did not solved it back in time

@giovannipollo hey I was able to solve it. I could raise a PR in case you wanted to use it.
