### ISSUE TITLE
Supported FINN layers

### ISSUE THREAD

**Issue by sefaburakokcu** [sefaburakokcu/quantized-yolov5#48]
Hi！first of all, thank you very much for your selfless sharing and updates, which have been very helpful for my learning. You mentioned earlier that quantized YOLOv5 cannot be exported for use with FINN. What are the main layers that are difficult to implement in this context? Do you have any good ideas for replacing these layers?

_Originally posted by @ramyen1 in https://github.com/sefaburakokcu/quantized-yolov5/issues/36#issuecomment-1903191542_

**Comment by sefaburakokcu** [comment]
Hi @ramyen1,

While working on our project, we found that FINN did not support some activation functions and the concat layer in Yolov5 initially. However, FINN has added support for some new layers in subsequent updates. You can check the layers in the FINN source code. Additionally, you may also find useful information about models and layers in the following links:

- [FINN Example Models](https://github.com/Xilinx/finn-examples?tab=readme-ov-file#example-neural-network-accelerators) 
- [Brevitas examples](https://github.com/Xilinx/brevitas/tree/master/src/brevitas_examples)

**Comment by ramyen1** [comment]
Hi @sefaburakokcu ,
Thank you for your kind reply. On my dataset, the mAP of your quantized YOLOv5 is more than 0.1 higher than YOLOv3. Therefore, I would like to continue trying the deployment of YOLOv5. Anyway, I am very grateful for your open-source code and helpful responses. Thanks again!

**Comment by sefaburakokcu** [comment]
Hi @ramyen1,

It's great news that the quantized YOLOv5 is showing promising results on your dataset. If you have any more questions or need further assistance during your work, feel free to reach out. Thanks for your kind words, and best of luck with your continued efforts!
